name: "Publish github pages"
on:
  push:
    branches:
      - gh-pages
jobs:
  build-deploy:
    name: "build and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@master
      - name: "setup node"
        uses: actions/setup-node@v1
        with:
          node-version: "13.7.0"
      - name: "install node_modules"
        run: yarn install
      - name: "generate static page"
        run: yarn generate
      - name: "test"
        run: yarn test
      - name: "deploy"
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./dist
